// Code generated by xgen. DO NOT EDIT.

package schema

// ChallengeTransactionRequest is The OFX element "CHALLENGETRNRQ" is of type "ChallengeTransactionRequest"
type ChallengeTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType `xml:"OFXEXTENSION"`
	CHALLENGERQ  *ChallengeRequest `xml:"CHALLENGERQ"`
	*AbstractTransactionRequest
}

// ChallengeTransactionResponse is The OFX element "CHALLENGETRNRS" is of type "ChallengeTransactionResponse"
type ChallengeTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType  `xml:"OFXEXTENSION"`
	CHALLENGERS  *ChallengeResponse `xml:"CHALLENGERS"`
	*AbstractTransactionResponse
}

// PinChangeTransactionRequest is The OFX element "PINCHTRNRQ" is of type "PinChangeTransactionRequest"
type PinChangeTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType `xml:"OFXEXTENSION"`
	PINCHRQ      *PinChangeRequest `xml:"PINCHRQ"`
	*AbstractTransactionRequest
}

// PinChangeTransactionResponse is The OFX element "PINCHTRNRS" is of type "PinChangeTransactionResponse"
type PinChangeTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType  `xml:"OFXEXTENSION"`
	PINCHRS      *PinChangeResponse `xml:"PINCHRS"`
	*AbstractTransactionResponse
}

// MFAChallengeTransactionRequest is The OFX element "MFACHALLENGETRNRQ" is of type "MFAChallengeTransactionRequest"
type MFAChallengeTransactionRequest struct {
	OFXEXTENSION   *OFXExtensionType    `xml:"OFXEXTENSION"`
	MFACHALLENGERQ *MFAChallengeRequest `xml:"MFACHALLENGERQ"`
	*AbstractTransactionRequest
}

// MFAChallengeTransactionResponse is The OFX element "MFACHALLENGETRNRS" is of type "MFAChallengeTransactionResponse"
type MFAChallengeTransactionResponse struct {
	OFXEXTENSION   *OFXExtensionType     `xml:"OFXEXTENSION"`
	MFACHALLENGERS *MFAChallengeResponse `xml:"MFACHALLENGERS"`
	*AbstractTransactionResponse
}
