// Code generated by xgen. DO NOT EDIT.

package schema

// LoanTransactionList is The OFX element "LOANTRANLIST" is of type "LoanTransactionList"
type LoanTransactionList struct {
	DTSTART     string                      `xml:"DTSTART"`
	DTEND       string                      `xml:"DTEND"`
	LOANSTMTTRN []*LoanStatementTransaction `xml:"LOANSTMTTRN"`
}

// LoanStatementTransaction is The OFX element "LOANSTMTTRN" is of type "LoanStatementTransaction"
type LoanStatementTransaction struct {
	LOANTRNTYPE   string                 `xml:"LOANTRNTYPE"`
	DTPOSTED      string                 `xml:"DTPOSTED"`
	DTUSER        string                 `xml:"DTUSER"`
	TRNAMT        string                 `xml:"TRNAMT"`
	LOANTRNAMT    *LoanTransactionAmount `xml:"LOANTRNAMT"`
	FITID         string                 `xml:"FITID"`
	CORRECTFITID  string                 `xml:"CORRECTFITID"`
	CORRECTACTION string                 `xml:"CORRECTACTION"`
	SRVRTID       string                 `xml:"SRVRTID"`
	CHECKNUM      string                 `xml:"CHECKNUM"`
	REFNUM        string                 `xml:"REFNUM"`
	NAME          string                 `xml:"NAME"`
	EXTDNAME      string                 `xml:"EXTDNAME"`
	LOANACCTTO    *LoanAccount           `xml:"LOANACCTTO"`
	BANKACCTTO    *BankAccount           `xml:"BANKACCTTO"`
	MEMO          string                 `xml:"MEMO"`
	IMAGEDATA     *ImageData             `xml:"IMAGEDATA"`
	CURRENCY      *Currency              `xml:"CURRENCY"`
	ORIGCURRENCY  *Currency              `xml:"ORIGCURRENCY"`
}

// AmortizationTransaction is The OFX element "AMRTSTMTTRN" is of type "AmortizationTransaction"
type AmortizationTransaction struct {
	PMTNUMBER   string                 `xml:"PMTNUMBER"`
	LOANINITBAL string                 `xml:"LOANINITBAL"`
	PRINBAL     *PrincipalBalanceType  `xml:"PRINBAL"`
	LOANTRNAMT  *LoanTransactionAmount `xml:"LOANTRNAMT"`
	LOANIRATE   *LoanRateType          `xml:"LOANIRATE"`
	AMRTTYPE    string                 `xml:"AMRTTYPE"`
}

// LoanClosing is The OFX element "LOANCLOSING" is of type "LoanClosing"
type LoanClosing struct {
	FITID        string                `xml:"FITID"`
	DTOPEN       string                `xml:"DTOPEN"`
	DTCLOSE      string                `xml:"DTCLOSE"`
	DTNEXT       string                `xml:"DTNEXT"`
	BALOPEN      string                `xml:"BALOPEN"`
	PRINBAL      *PrincipalBalanceType `xml:"PRINBAL"`
	LOANINT      *LoanInterestType     `xml:"LOANINT"`
	LOANRATE     *LoanRateType         `xml:"LOANRATE"`
	ESTPAYOFF    *EstimatedPayoff      `xml:"ESTPAYOFF"`
	BALLOONAMT   string                `xml:"BALLOONAMT"`
	LOANPMT      *LoanPaymentAmount    `xml:"LOANPMT"`
	LOANRMNPMTS  string                `xml:"LOANRMNPMTS"`
	BALLIST      *BalanceList          `xml:"BALLIST"`
	TAXYTD       string                `xml:"TAXYTD"`
	ESCRWBAL     *EscrowBalance        `xml:"ESCRWBAL"`
	DTPOSTSTART  string                `xml:"DTPOSTSTART"`
	DTPOSTEND    string                `xml:"DTPOSTEND"`
	AUTOPAY      string                `xml:"AUTOPAY"`
	LASTPMTINFO  *LastPmtInfoType      `xml:"LASTPMTINFO"`
	MKTGINFO     string                `xml:"MKTGINFO"`
	IMAGEDATA    *ImageData            `xml:"IMAGEDATA"`
	CURRENCY     *Currency             `xml:"CURRENCY"`
	ORIGCURRENCY *Currency             `xml:"ORIGCURRENCY"`
}

// EstimatedPayoff is The OFX element "ESTPAYOFF" is of type "EstimatedPayoff"
type EstimatedPayoff struct {
	ESTPAYOFFBAL string `xml:"ESTPAYOFFBAL"`
	DTASOF       string `xml:"DTASOF"`
}

// EscrowBalance is The OFX element "ESCRWBAL" is of type "EscrowBalance"
type EscrowBalance struct {
	BALAMT        string `xml:"BALAMT"`
	ESCRWTAXBAL   string `xml:"ESCRWTAXBAL"`
	ESCRWINSBAL   string `xml:"ESCRWINSBAL"`
	ESCRWPMIBAL   string `xml:"ESCRWPMIBAL"`
	ESCRWFEESBAL  string `xml:"ESCRWFEESBAL"`
	ESCRWOTHERBAL string `xml:"ESCRWOTHERBAL"`
	DTASOF        string `xml:"DTASOF"`
}

// LoanTransactionEnum is The OFX element "LOANTRNTYPE" is of type "LoanTransactionEnum"
type LoanTransactionEnum string

// LoanPaymentNumber is The OFX element "PMTNUMBER" is of type "LoanPaymentNumber"
type LoanPaymentNumber string

// AmortizationType is The OFX element "AMRTTYPE" is of type "AmortizationType"
type AmortizationType string
