// Code generated by xgen. DO NOT EDIT.

package schema

// LoanStatementRequest is The OFX element "LOANSTMTRQ" is of type "LoanStatementRequest"
type LoanStatementRequest struct {
	LOANACCTFROM *LoanAccount    `xml:"LOANACCTFROM"`
	INCTRAN      *IncTransaction `xml:"INCTRAN"`
	INCTRANIMG   string          `xml:"INCTRANIMG"`
}

// LoanStatementResponse is The OFX element "LOANSTMTRS" is of type "LoanStatementResponse"
type LoanStatementResponse struct {
	CURDEF       string                `xml:"CURDEF"`
	LOANACCTFROM *LoanAccount          `xml:"LOANACCTFROM"`
	LOANTRANLIST *LoanTransactionList  `xml:"LOANTRANLIST"`
	PRINBAL      *PrincipalBalanceType `xml:"PRINBAL"`
	AVAILBAL     *AvailableBalance     `xml:"AVAILBAL"`
	MKTGINFO     string                `xml:"MKTGINFO"`
}

// AmortizationRequest is The OFX element "AMRTSTMTRQ" is of type "AmortizationRequest"
type AmortizationRequest struct {
	LOANACCTFROM *LoanAccount `xml:"LOANACCTFROM"`
	DTSTART      string       `xml:"DTSTART"`
	DTEND        string       `xml:"DTEND"`
}

// AmortizationResponse is The OFX element "AMRTSTMTRS" is of type "AmortizationResponse"
type AmortizationResponse struct {
	CURDEF       string                       `xml:"CURDEF"`
	LOANACCTFROM *LoanAccount                 `xml:"LOANACCTFROM"`
	AMRTTRANLIST *AmortizationTransactionList `xml:"AMRTTRANLIST"`
	MKTGINFO     string                       `xml:"MKTGINFO"`
}

// AmortizationTransactionList is The OFX element "AMRTSTMTRS" is of type "AmortizationResponse"
type AmortizationTransactionList struct {
	DTSTART     string                     `xml:"DTSTART"`
	DTEND       string                     `xml:"DTEND"`
	AMRTSTMTTRN []*AmortizationTransaction `xml:"AMRTSTMTTRN"`
}

// LoanStatementEndRequest is The OFX element "LOANSTMTENDRQ" is of type "LoanStatementEndRequest"
type LoanStatementEndRequest struct {
	LOANACCTFROM *LoanAccount `xml:"LOANACCTFROM"`
	DTSTART      string       `xml:"DTSTART"`
	DTEND        string       `xml:"DTEND"`
}

// LoanStatementEndResponse is The OFX element "LOANSTMTENDRS" is of type "LoanStatementEndResponse"
type LoanStatementEndResponse struct {
	CURDEF       string         `xml:"CURDEF"`
	LOANACCTFROM *LoanAccount   `xml:"LOANACCTFROM"`
	LOANCLOSING  []*LoanClosing `xml:"LOANCLOSING"`
}

// LoanMailRequest is The OFX element "LOANMAILRQ" is of type "LoanMailRequest"
type LoanMailRequest struct {
	LOANACCTFROM *LoanAccount `xml:"LOANACCTFROM"`
	MAIL         *Mail        `xml:"MAIL"`
}

// LoanMailResponse is The OFX element "LOANMAILRS" is of type "LoanMailResponse"
type LoanMailResponse struct {
	LOANACCTFROM *LoanAccount `xml:"LOANACCTFROM"`
	MAIL         *Mail        `xml:"MAIL"`
}
