// Code generated by xgen. DO NOT EDIT.

package gofx

// AbstractPayeeRequest ...
type AbstractPayeeRequest struct {
}

// PayeeRequest is The OFX element "PAYEERQ" is of type "PayeeRequest"
type PayeeRequest struct {
	PAYEEID    string       `xml:"PAYEEID"`
	PAYEE      *Payee       `xml:"PAYEE"`
	BANKACCTTO *BankAccount `xml:"BANKACCTTO"`
	PAYACCT    []string     `xml:"PAYACCT"`
	*AbstractPayeeRequest
}

// PayeeModRequest is The OFX element "PAYEEMODRQ" is of type "PayeeModRequest"
type PayeeModRequest struct {
	PAYEELSTID string       `xml:"PAYEELSTID"`
	PAYEE      *Payee       `xml:"PAYEE"`
	BANKACCTTO *BankAccount `xml:"BANKACCTTO"`
	PAYACCT    []string     `xml:"PAYACCT"`
	*AbstractPayeeRequest
}

// PayeeDeleteRequest is The OFX element "PAYEEDELRQ" is of type "PayeeDeleteRequest"
type PayeeDeleteRequest struct {
	PAYEELSTID string `xml:"PAYEELSTID"`
	*AbstractPayeeRequest
}

// AbstractPayeeResponse ...
type AbstractPayeeResponse struct {
	PAYEELSTID string `xml:"PAYEELSTID"`
}

// PayeeResponse is The OFX element "PAYEERS" is of type "PayeeResponse"
type PayeeResponse struct {
	PAYEE      *Payee         `xml:"PAYEE"`
	BANKACCTTO *BankAccount   `xml:"BANKACCTTO"`
	EXTDPAYEE  *ExtendedPayee `xml:"EXTDPAYEE"`
	PAYACCT    []string       `xml:"PAYACCT"`
	*AbstractPayeeResponse
}

// PayeeModResponse is The OFX element "PAYEEMODRS" is of type "PayeeModResponse"
type PayeeModResponse struct {
	PAYEE      *Payee         `xml:"PAYEE"`
	BANKACCTTO *BankAccount   `xml:"BANKACCTTO"`
	PAYACCT    []string       `xml:"PAYACCT"`
	EXTDPAYEE  *ExtendedPayee `xml:"EXTDPAYEE"`
	*AbstractPayeeResponse
}

// PayeeDeleteResponse is The OFX element "PAYEEDELRS" is of type "PayeeDeleteResponse"
type PayeeDeleteResponse struct {
	*AbstractPayeeResponse
}

// PaymentInquiryResponse is The OFX element "PMTINQRS" is of type "PaymentInquiryResponse"
type PaymentInquiryResponse struct {
	SRVRTID   string                   `xml:"SRVRTID"`
	PMTPRCSTS *PaymentProcessingStatus `xml:"PMTPRCSTS"`
	CHECKNUM  string                   `xml:"CHECKNUM"`
}

// PaymentMailRequest is The OFX element "PMTMAILRQ" is of type "PaymentMailRequest"
type PaymentMailRequest struct {
	MAIL    *Mail        `xml:"MAIL"`
	SRVRTID string       `xml:"SRVRTID"`
	PMTINFO *PaymentInfo `xml:"PMTINFO"`
}

// PaymentMailResponse is The OFX element "PMTMAILRS" is of type "PaymentMailResponse"
type PaymentMailResponse struct {
	MAIL    *Mail        `xml:"MAIL"`
	SRVRTID string       `xml:"SRVRTID"`
	PMTINFO *PaymentInfo `xml:"PMTINFO"`
}

// AbstractPaymentRequest ...
type AbstractPaymentRequest struct {
}

// PaymentRequest is The OFX element "PMTRQ" is of type "PaymentRequest"
type PaymentRequest struct {
	PMTINFO *PaymentInfo `xml:"PMTINFO"`
	*AbstractPaymentRequest
}

// PaymentModRequest is The OFX element "PMTMODRQ" is of type "PaymentModRequest"
type PaymentModRequest struct {
	SRVRTID string       `xml:"SRVRTID"`
	PMTINFO *PaymentInfo `xml:"PMTINFO"`
	*AbstractPaymentRequest
}

// PaymentCancelRequest is The OFX element "PMTCANCRQ" is of type "PaymentCancelRequest"
type PaymentCancelRequest struct {
	SRVRTID string `xml:"SRVRTID"`
	*AbstractPaymentRequest
}

// PaymentInquiryRequest is The OFX element "PMTINQRQ" is of type "PaymentInquiryRequest"
type PaymentInquiryRequest struct {
	SRVRTID string `xml:"SRVRTID"`
}

// AbstractPaymentResponse ...
type AbstractPaymentResponse struct {
	SRVRTID string `xml:"SRVRTID"`
}

// PaymentResponse is The OFX element "PMTRS" is of type "PaymentResponse"
type PaymentResponse struct {
	PAYEELSTID string                   `xml:"PAYEELSTID"`
	CURDEF     string                   `xml:"CURDEF"`
	PMTINFO    *PaymentInfo             `xml:"PMTINFO"`
	EXTDPAYEE  *ExtendedPayee           `xml:"EXTDPAYEE"`
	CHECKNUM   string                   `xml:"CHECKNUM"`
	PMTPRCSTS  *PaymentProcessingStatus `xml:"PMTPRCSTS"`
	RECSRVRTID string                   `xml:"RECSRVRTID"`
	*AbstractPaymentResponse
}

// PaymentModResponse is The OFX element "PMTMODRS" is of type "PaymentModResponse"
type PaymentModResponse struct {
	PMTINFO   *PaymentInfo             `xml:"PMTINFO"`
	PMTPRCSTS *PaymentProcessingStatus `xml:"PMTPRCSTS"`
	*AbstractPaymentResponse
}

// PaymentCancelResponse is The OFX element "PMTCANCRS" is of type "PaymentCancelResponse"
type PaymentCancelResponse struct {
	*AbstractPaymentResponse
}

// AbstractRecurringPaymentRequest ...
type AbstractRecurringPaymentRequest struct {
}

// AbstractRecurringPaymentResponse ...
type AbstractRecurringPaymentResponse struct {
	RECSRVRTID string `xml:"RECSRVRTID"`
}

// RecurringPaymentCancelRequest is The OFX element "RECPMTCANCRQ" is of type "RecurringPaymentCancelRequest"
type RecurringPaymentCancelRequest struct {
	RECSRVRTID string `xml:"RECSRVRTID"`
	CANPENDING string `xml:"CANPENDING"`
	*AbstractRecurringPaymentRequest
}

// RecurringPaymentCancelResponse is The OFX element "RECPMTCANCRS" is of type "RecurringPaymentCancelResponse"
type RecurringPaymentCancelResponse struct {
	CANPENDING string `xml:"CANPENDING"`
	*AbstractRecurringPaymentResponse
}

// RecurringPaymentModRequest is The OFX element "RECPMTMODRQ" is of type "RecurringPaymentModRequest"
type RecurringPaymentModRequest struct {
	RECSRVRTID string                 `xml:"RECSRVRTID"`
	RECURRINST *RecurringInstructions `xml:"RECURRINST"`
	PMTINFO    *PaymentInfo           `xml:"PMTINFO"`
	INITIALAMT string                 `xml:"INITIALAMT"`
	FINALAMT   string                 `xml:"FINALAMT"`
	MODPENDING string                 `xml:"MODPENDING"`
	*AbstractRecurringPaymentRequest
}

// RecurringPaymentModResponse is The OFX element "RECPMTMODRS" is of type "RecurringPaymentModResponse"
type RecurringPaymentModResponse struct {
	RECURRINST *RecurringInstructions `xml:"RECURRINST"`
	PMTINFO    *PaymentInfo           `xml:"PMTINFO"`
	INITIALAMT string                 `xml:"INITIALAMT"`
	FINALAMT   string                 `xml:"FINALAMT"`
	MODPENDING string                 `xml:"MODPENDING"`
	*AbstractRecurringPaymentResponse
}

// RecurringPaymentRequest is The OFX element "RECPMTRQ" is of type "RecurringPaymentRequest"
type RecurringPaymentRequest struct {
	RECURRINST *RecurringInstructions `xml:"RECURRINST"`
	PMTINFO    *PaymentInfo           `xml:"PMTINFO"`
	INITIALAMT string                 `xml:"INITIALAMT"`
	FINALAMT   string                 `xml:"FINALAMT"`
	*AbstractRecurringPaymentRequest
}

// RecurringPaymentResponse is The OFX element "RECPMTRS" is of type "RecurringPaymentResponse"
type RecurringPaymentResponse struct {
	PAYEELSTID string                 `xml:"PAYEELSTID"`
	CURDEF     string                 `xml:"CURDEF"`
	RECURRINST *RecurringInstructions `xml:"RECURRINST"`
	PMTINFO    *PaymentInfo           `xml:"PMTINFO"`
	INITIALAMT string                 `xml:"INITIALAMT"`
	FINALAMT   string                 `xml:"FINALAMT"`
	EXTDPAYEE  *ExtendedPayee         `xml:"EXTDPAYEE"`
	*AbstractRecurringPaymentResponse
}
