// Code generated by xgen. DO NOT EDIT.

package gofx

// WireSyncRequest is The OFX element "WIRESYNCRQ" is of type "WireSyncRequest"
type WireSyncRequest struct {
	BANKACCTFROM *BankAccount              `xml:"BANKACCTFROM"`
	OFXEXTENSION *OFXExtensionType         `xml:"OFXEXTENSION"`
	WIRETRNRQ    []*WireTransactionRequest `xml:"WIRETRNRQ"`
	*AbstractSyncRequest
}

// WireSyncResponse is The OFX element "WIRESYNCRS" is of type "WireSyncResponse"
type WireSyncResponse struct {
	BANKACCTFROM *BankAccount               `xml:"BANKACCTFROM"`
	OFXEXTENSION *OFXExtensionType          `xml:"OFXEXTENSION"`
	WIRETRNRS    []*WireTransactionResponse `xml:"WIRETRNRS"`
	*AbstractSyncResponse
}

// WireTransactionRequest is The OFX element "WIRETRNRQ" is of type "WireTransactionRequest"
type WireTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType        `xml:"OFXEXTENSION"`
	WIRERQ       *WireRequest             `xml:"WIRERQ"`
	WIRECANRQ    *WireCancellationRequest `xml:"WIRECANRQ"`
	*AbstractTransactionRequest
}

// WireTransactionResponse is The OFX element "WIRETRNRS" is of type "WireTransactionResponse"
type WireTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType         `xml:"OFXEXTENSION"`
	WIRERS       *WireResponse             `xml:"WIRERS"`
	WIRECANRS    *WireCancellationResponse `xml:"WIRECANRS"`
	*AbstractTransactionResponse
}
