// Code generated by xgen. DO NOT EDIT.

package gofx

// BillPaymentstatusCodeEnum is The OFX element "BILLPMTSTATUSCODEENUM" is of type "BillPaymentstatusCodeEnum"
type BillPaymentstatusCodeEnum string

// BillStatusCodeEnum is The OFX element "BILLSTATUSCODEENUM" is of type "BillStatusCodeEnum"
type BillStatusCodeEnum string

// BillTypeEnum is The OFX element "BILLTYPEENUM" is of type "BillTypeEnum"
type BillTypeEnum string

// StatusModBYEnum is The OFX element "STATUSMODBYENUM" is of type "StatusModBYEnum"
type StatusModBYEnum string

// ColumnType is The OFX element "COLUMN" is of type "ColumnType"
type ColumnType string

// BillDetailRow is The OFX element "BILLDETAILROW" is of type "BillDetailRow"
type BillDetailRow struct {
	C []string `xml:"C"`
	N []string `xml:"N"`
}

// BillDetailTable is The OFX element "BILLDETAILTABLE" is of type "BillDetailTable"
type BillDetailTable struct {
	TABLENAME           string           `xml:"TABLENAME"`
	BILLDETAILTABLETYPE string           `xml:"BILLDETAILTABLETYPE"`
	BILLDETAILROW       []*BillDetailRow `xml:"BILLDETAILROW"`
}

// BillPaymentstatus is The OFX element "BILLPMTSTATUS" is of type "BillPaymentstatus"
type BillPaymentstatus struct {
	SRVRTID           string `xml:"SRVRTID"`
	BILLPMTSTATUSCODE string `xml:"BILLPMTSTATUSCODE"`
	DTEFF             string `xml:"DTEFF"`
	STATUSMODBY       string `xml:"STATUSMODBY"`
}

// BillPaymentstatusCounts is The OFX element "BILLPMTSTATUSCOUNTS" is of type "BillPaymentstatusCounts"
type BillPaymentstatusCounts struct {
	BILLPMTSTATUSCODE string `xml:"BILLPMTSTATUSCODE"`
	COUNT             string `xml:"COUNT"`
}

// BillStatus is The OFX element "BILLSTATUS" is of type "BillStatus"
type BillStatus struct {
	BILLSTATUSCODE string `xml:"BILLSTATUSCODE"`
	DTEFF          string `xml:"DTEFF"`
	STATUSMODBY    string `xml:"STATUSMODBY"`
}

// BillStatusCounts is The OFX element "BILLSTATUSCOUNTS" is of type "BillStatusCounts"
type BillStatusCounts struct {
	BILLSTATUSCODE string `xml:"BILLSTATUSCODE"`
	COUNT          string `xml:"COUNT"`
}

// ColumnDefinition is The OFX element "COLDEF" is of type "ColumnDefinition"
type ColumnDefinition struct {
	COLNAME string `xml:"COLNAME"`
	COLTYPE string `xml:"COLTYPE"`
}

// PresentmentBillInfo is The OFX element "PRESBILLINFO" is of type "PresentmentBillInfo"
type PresentmentBillInfo struct {
	BILLID          string               `xml:"BILLID"`
	PRESACCTFROM    *PresentmentAccount  `xml:"PRESACCTFROM"`
	PAYEEID         string               `xml:"PAYEEID"`
	BILLREFINFO     string               `xml:"BILLREFINFO"`
	AMTDUE          string               `xml:"AMTDUE"`
	MINAMTDUE       string               `xml:"MINAMTDUE"`
	DTPMTDUE        string               `xml:"DTPMTDUE"`
	DTBILL          string               `xml:"DTBILL"`
	DTOPEN          string               `xml:"DTOPEN"`
	DTCLOSE         string               `xml:"DTCLOSE"`
	PREVBAL         string               `xml:"PREVBAL"`
	ACTIVITY        string               `xml:"ACTIVITY"`
	ACCTBAL         string               `xml:"ACCTBAL"`
	INVOICE         *Invoice             `xml:"INVOICE"`
	NOTIFYDESIRED   string               `xml:"NOTIFYDESIRED"`
	BILLTYPE        string               `xml:"BILLTYPE"`
	BILLSTATUS      []*BillStatus        `xml:"BILLSTATUS"`
	BILLPMTSTATUS   []*BillPaymentstatus `xml:"BILLPMTSTATUS"`
	STMNTIMAGE      *StatementImage      `xml:"STMNTIMAGE"`
	DETAILAVAILABLE string               `xml:"DETAILAVAILABLE"`
	BILLDETAILTABLE *BillDetailTable     `xml:"BILLDETAILTABLE"`
}

// PresentmentCounts is The OFX element "PRESCOUNTS" is of type "PresentmentCounts"
type PresentmentCounts struct {
	BILLSTATUSCOUNTS    []*BillStatusCounts        `xml:"BILLSTATUSCOUNTS"`
	BILLPMTSTATUSCOUNTS []*BillPaymentstatusCounts `xml:"BILLPMTSTATUSCOUNTS"`
}

// PresentmentDeliveryId is The OFX element "PRESDELIVERYID" is of type "PresentmentDeliveryId"
type PresentmentDeliveryId struct {
	PRESACCTFROM *PresentmentAccount `xml:"PRESACCTFROM"`
	BILLID       string              `xml:"BILLID"`
	DTSEEN       string              `xml:"DTSEEN"`
}

// PresentmentDetail is The OFX element "PRESDETAIL" is of type "PresentmentDetail"
type PresentmentDetail struct {
	BILLID          string              `xml:"BILLID"`
	PRESACCTFROM    *PresentmentAccount `xml:"PRESACCTFROM"`
	BILLDETAILTABLE []*BillDetailTable  `xml:"BILLDETAILTABLE"`
}

// PresentmentList is The OFX element "PRESLIST" is of type "PresentmentList"
type PresentmentList struct {
	PRESBILLINFO []*PresentmentBillInfo `xml:"PRESBILLINFO"`
}

// StatementImage is The OFX element "STMNTIMAGE" is of type "StatementImage"
type StatementImage struct {
	IMAGEURL    string   `xml:"IMAGEURL"`
	PREFETCHURL []string `xml:"PREFETCHURL"`
	DTEXPIRE    string   `xml:"DTEXPIRE"`
}
