// Code generated by xgen. DO NOT EDIT.

package gofx

// BankMailRequest is The OFX element "BANKMAILRQ" is of type "BankMailRequest"
type BankMailRequest struct {
	BANKACCTFROM *BankAccount       `xml:"BANKACCTFROM"`
	CCACCTFROM   *CreditCardAccount `xml:"CCACCTFROM"`
	MAIL         *Mail              `xml:"MAIL"`
}

// AbstractMailResponse ...
type AbstractMailResponse struct {
}

// BankMailResponse is The OFX element "BANKMAILRS" is of type "BankMailResponse"
type BankMailResponse struct {
	BANKACCTFROM *BankAccount       `xml:"BANKACCTFROM"`
	CCACCTFROM   *CreditCardAccount `xml:"CCACCTFROM"`
	MAIL         *Mail              `xml:"MAIL"`
	*AbstractMailResponse
}

// CheckMailResponse is The OFX element "CHKMAILRS" is of type "CheckMailResponse"
type CheckMailResponse struct {
	BANKACCTFROM *BankAccount `xml:"BANKACCTFROM"`
	MAIL         *Mail        `xml:"MAIL"`
	CHECKNUM     string       `xml:"CHECKNUM"`
	TRNAMT       string       `xml:"TRNAMT"`
	DTUSER       string       `xml:"DTUSER"`
	FEE          string       `xml:"FEE"`
	*AbstractMailResponse
}

// DepositMailResponse is The OFX element "DEPMAILRS" is of type "DepositMailResponse"
type DepositMailResponse struct {
	BANKACCTFROM *BankAccount `xml:"BANKACCTFROM"`
	MAIL         *Mail        `xml:"MAIL"`
	TRNAMT       string       `xml:"TRNAMT"`
	DTUSER       string       `xml:"DTUSER"`
	FEE          string       `xml:"FEE"`
	*AbstractMailResponse
}

// AbstractIntraRequest ...
type AbstractIntraRequest struct {
}

// AbstractIntraResponse ...
type AbstractIntraResponse struct {
}

// IntraCancellationRequest is The OFX element "INTRACANRQ" is of type "IntraCancellationRequest"
type IntraCancellationRequest struct {
	SRVRTID string `xml:"SRVRTID"`
	*AbstractIntraRequest
}

// IntraCancellationResponse is The OFX element "INTRACANRS" is of type "IntraCancellationResponse"
type IntraCancellationResponse struct {
	SRVRTID string `xml:"SRVRTID"`
	*AbstractIntraResponse
}

// IntraModRequest is The OFX element "INTRAMODRQ" is of type "IntraModRequest"
type IntraModRequest struct {
	SRVRTID  string        `xml:"SRVRTID"`
	XFERINFO *TransferInfo `xml:"XFERINFO"`
	*AbstractIntraRequest
}

// IntraModResponse is The OFX element "INTRAMODRS" is of type "IntraModResponse"
type IntraModResponse struct {
	SRVRTID    string                    `xml:"SRVRTID"`
	XFERINFO   *TransferInfo             `xml:"XFERINFO"`
	XFERPRCSTS *TransferProcessingStatus `xml:"XFERPRCSTS"`
	*AbstractIntraResponse
}

// IntraRequest is The OFX element "INTRARQ" is of type "IntraRequest"
type IntraRequest struct {
	XFERINFO *TransferInfo `xml:"XFERINFO"`
	*AbstractIntraRequest
}

// IntraResponse is The OFX element "INTRARS" is of type "IntraResponse"
type IntraResponse struct {
	CURDEF     string                    `xml:"CURDEF"`
	SRVRTID    string                    `xml:"SRVRTID"`
	XFERINFO   *TransferInfo             `xml:"XFERINFO"`
	DTXFERPRJ  string                    `xml:"DTXFERPRJ"`
	DTPOSTED   string                    `xml:"DTPOSTED"`
	RECSRVRTID string                    `xml:"RECSRVRTID"`
	XFERPRCSTS *TransferProcessingStatus `xml:"XFERPRCSTS"`
	*AbstractIntraResponse
}

// AbstractRecurringIntraRequest ...
type AbstractRecurringIntraRequest struct {
}

// AbstractRecurringIntraResponse ...
type AbstractRecurringIntraResponse struct {
}

// RecurringIntraCancellationRequest is The OFX element "RECINTRACANRQ" is of type "RecurringIntraCancellationRequest"
type RecurringIntraCancellationRequest struct {
	RECSRVRTID string `xml:"RECSRVRTID"`
	CANPENDING string `xml:"CANPENDING"`
	*AbstractRecurringIntraRequest
}

// RecurringIntraCancellationResponse is The OFX element "RECINTRACANRS" is of type "RecurringIntraCancellationResponse"
type RecurringIntraCancellationResponse struct {
	RECSRVRTID string `xml:"RECSRVRTID"`
	CANPENDING string `xml:"CANPENDING"`
	*AbstractRecurringIntraResponse
}

// RecurringIntraModRequest is The OFX element "RECINTRAMODRQ" is of type "RecurringIntraModRequest"
type RecurringIntraModRequest struct {
	RECSRVRTID string                 `xml:"RECSRVRTID"`
	RECURRINST *RecurringInstructions `xml:"RECURRINST"`
	INTRARQ    *IntraRequest          `xml:"INTRARQ"`
	MODPENDING string                 `xml:"MODPENDING"`
	*AbstractRecurringIntraRequest
}

// RecurringIntraModResponse is The OFX element "RECINTRAMODRS" is of type "RecurringIntraModResponse"
type RecurringIntraModResponse struct {
	RECSRVRTID string                 `xml:"RECSRVRTID"`
	RECURRINST *RecurringInstructions `xml:"RECURRINST"`
	INTRARS    *IntraResponse         `xml:"INTRARS"`
	MODPENDING string                 `xml:"MODPENDING"`
	*AbstractRecurringIntraResponse
}

// RecurringIntraRequest is The OFX element "RECINTRARQ" is of type "RecurringIntraRequest"
type RecurringIntraRequest struct {
	RECURRINST *RecurringInstructions `xml:"RECURRINST"`
	INTRARQ    *IntraRequest          `xml:"INTRARQ"`
	*AbstractRecurringIntraRequest
}

// RecurringIntraResponse is The OFX element "RECINTRARS" is of type "RecurringIntraResponse"
type RecurringIntraResponse struct {
	RECSRVRTID string                 `xml:"RECSRVRTID"`
	RECURRINST *RecurringInstructions `xml:"RECURRINST"`
	INTRARS    *IntraResponse         `xml:"INTRARS"`
	*AbstractRecurringIntraResponse
}

// StatementEndRequest is The OFX element "STMTENDRQ" is of type "StatementEndRequest"
type StatementEndRequest struct {
	BANKACCTFROM *BankAccount `xml:"BANKACCTFROM"`
	DTSTART      string       `xml:"DTSTART"`
	DTEND        string       `xml:"DTEND"`
	INCSTMTIMG   string       `xml:"INCSTMTIMG"`
}

// StatementEndResponse is The OFX element "STMTENDRS" is of type "StatementEndResponse"
type StatementEndResponse struct {
	CURDEF       string       `xml:"CURDEF"`
	BANKACCTFROM *BankAccount `xml:"BANKACCTFROM"`
	CLOSING      []*Closing   `xml:"CLOSING"`
}

// StatementRequest is The OFX element "STMTRQ" is of type "StatementRequest"
type StatementRequest struct {
	BANKACCTFROM   *BankAccount    `xml:"BANKACCTFROM"`
	INCTRAN        *IncTransaction `xml:"INCTRAN"`
	INCLUDEPENDING string          `xml:"INCLUDEPENDING"`
	INCTRANIMG     string          `xml:"INCTRANIMG"`
}

// StatementResponse is The OFX element "STMTRS" is of type "StatementResponse"
type StatementResponse struct {
	CURDEF        string                  `xml:"CURDEF"`
	BANKACCTFROM  *BankAccount            `xml:"BANKACCTFROM"`
	BANKTRANLIST  *BankTransactionList    `xml:"BANKTRANLIST"`
	BANKTRANLISTP *PendingTransactionList `xml:"BANKTRANLISTP"`
	LEDGERBAL     *LedgerBalance          `xml:"LEDGERBAL"`
	AVAILBAL      *AvailableBalance       `xml:"AVAILBAL"`
	CASHADVBALAMT string                  `xml:"CASHADVBALAMT"`
	INTRATE       string                  `xml:"INTRATE"`
	BALLIST       *BalanceList            `xml:"BALLIST"`
	MKTGINFO      string                  `xml:"MKTGINFO"`
}

// StopCheckRequest is The OFX element "STPCHKRQ" is of type "StopCheckRequest"
type StopCheckRequest struct {
	BANKACCTFROM *BankAccount      `xml:"BANKACCTFROM"`
	CHKRANGE     *CheckRange       `xml:"CHKRANGE"`
	CHKDESC      *CheckDescription `xml:"CHKDESC"`
}

// StopCheckResponse is The OFX element "STPCHKRS" is of type "StopCheckResponse"
type StopCheckResponse struct {
	CURDEF       string             `xml:"CURDEF"`
	BANKACCTFROM *BankAccount       `xml:"BANKACCTFROM"`
	STPCHKNUM    []*StopCheckNumber `xml:"STPCHKNUM"`
	FEE          string             `xml:"FEE"`
	FEEMSG       string             `xml:"FEEMSG"`
}
