// Code generated by xgen. DO NOT EDIT.

package schema

// BankMailTransactionRequest is The OFX element "BANKMAILTRNRQ" is of type "BankMailTransactionRequest"
type BankMailTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType `xml:"OFXEXTENSION"`
	BANKMAILRQ   *BankMailRequest  `xml:"BANKMAILRQ"`
	*AbstractTransactionRequest
}

// BankMailTransactionResponse is The OFX element "BANKMAILTRNRS" is of type "BankMailTransactionResponse"
type BankMailTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType    `xml:"OFXEXTENSION"`
	BANKMAILRS   *BankMailResponse    `xml:"BANKMAILRS"`
	CHKMAILRS    *CheckMailResponse   `xml:"CHKMAILRS"`
	DEPMAILRS    *DepositMailResponse `xml:"DEPMAILRS"`
	*AbstractTransactionResponse
}

// IntraSyncRequest is The OFX element "INTRASYNCRQ" is of type "IntraSyncRequest"
type IntraSyncRequest struct {
	BANKACCTFROM *BankAccount               `xml:"BANKACCTFROM"`
	CCACCTFROM   *CreditCardAccount         `xml:"CCACCTFROM"`
	LOANACCTFROM *LoanAccount               `xml:"LOANACCTFROM"`
	OFXEXTENSION *OFXExtensionType          `xml:"OFXEXTENSION"`
	INTRATRNRQ   []*IntraTransactionRequest `xml:"INTRATRNRQ"`
	*AbstractSyncRequest
}

// IntraSyncResponse is The OFX element "INTRASYNCRS" is of type "IntraSyncResponse"
type IntraSyncResponse struct {
	BANKACCTFROM *BankAccount                `xml:"BANKACCTFROM"`
	CCACCTFROM   *CreditCardAccount          `xml:"CCACCTFROM"`
	LOANACCTFROM *LoanAccount                `xml:"LOANACCTFROM"`
	OFXEXTENSION *OFXExtensionType           `xml:"OFXEXTENSION"`
	INTRATRNRS   []*IntraTransactionResponse `xml:"INTRATRNRS"`
	*AbstractSyncResponse
}

// IntraTransactionRequest is The OFX element "INTRATRNRQ" is of type "IntraTransactionRequest"
type IntraTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType         `xml:"OFXEXTENSION"`
	INTRARQ      *IntraRequest             `xml:"INTRARQ"`
	INTRAMODRQ   *IntraModRequest          `xml:"INTRAMODRQ"`
	INTRACANRQ   *IntraCancellationRequest `xml:"INTRACANRQ"`
	*AbstractTransactionRequest
}

// IntraTransactionResponse is The OFX element "INTRATRNRS" is of type "IntraTransactionResponse"
type IntraTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType          `xml:"OFXEXTENSION"`
	INTRARS      *IntraResponse             `xml:"INTRARS"`
	INTRAMODRS   *IntraModResponse          `xml:"INTRAMODRS"`
	INTRACANRS   *IntraCancellationResponse `xml:"INTRACANRS"`
	*AbstractTransactionResponse
}

// StopCheckSyncRequest is The OFX element "STPCHKSYNCRQ" is of type "StopCheckSyncRequest"
type StopCheckSyncRequest struct {
	BANKACCTFROM *BankAccount                   `xml:"BANKACCTFROM"`
	OFXEXTENSION *OFXExtensionType              `xml:"OFXEXTENSION"`
	STPCHKTRNRQ  []*StopCheckTransactionRequest `xml:"STPCHKTRNRQ"`
	*AbstractSyncRequest
}

// StopCheckSyncResponse is The OFX element "STPCHKSYNCRS" is of type "StopCheckSyncResponse"
type StopCheckSyncResponse struct {
	BANKACCTFROM *BankAccount                    `xml:"BANKACCTFROM"`
	OFXEXTENSION *OFXExtensionType               `xml:"OFXEXTENSION"`
	STPCHKTRNRS  []*StopCheckTransactionResponse `xml:"STPCHKTRNRS"`
	*AbstractSyncResponse
}

// StopCheckTransactionRequest is The OFX element "STPCHKTRNRQ" is of type "StopCheckTransactionRequest"
type StopCheckTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType `xml:"OFXEXTENSION"`
	STPCHKRQ     *StopCheckRequest `xml:"STPCHKRQ"`
	*AbstractTransactionRequest
}

// StopCheckTransactionResponse is The OFX element "STPCHKTRNRS" is of type "StopCheckTransactionResponse"
type StopCheckTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType  `xml:"OFXEXTENSION"`
	STPCHKRS     *StopCheckResponse `xml:"STPCHKRS"`
	*AbstractTransactionResponse
}

// StatementTransactionRequest is The OFX element "STMTTRNRQ" is of type "StatementTransactionRequest"
type StatementTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType `xml:"OFXEXTENSION"`
	STMTRQ       *StatementRequest `xml:"STMTRQ"`
	*AbstractTransactionRequest
}

// StatementTransactionResponse is The OFX element "STMTTRNRS" is of type "StatementTransactionResponse"
type StatementTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType  `xml:"OFXEXTENSION"`
	STMTRS       *StatementResponse `xml:"STMTRS"`
	*AbstractTransactionResponse
}

// StatementEndTransactionRequest is The OFX element "STMTENDTRNRQ" is of type "StatementEndTransactionRequest"
type StatementEndTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType    `xml:"OFXEXTENSION"`
	STMTENDRQ    *StatementEndRequest `xml:"STMTENDRQ"`
	*AbstractTransactionRequest
}

// StatementEndTransactionResponse is The OFX element "STMTENDTRNRS" is of type "StatementEndTransactionResponse"
type StatementEndTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType     `xml:"OFXEXTENSION"`
	STMTENDRS    *StatementEndResponse `xml:"STMTENDRS"`
	*AbstractTransactionResponse
}

// RecurringIntraSyncRequest is The OFX element "RECINTRASYNCRQ" is of type "RecurringIntraSyncRequest"
type RecurringIntraSyncRequest struct {
	BANKACCTFROM  *BankAccount                        `xml:"BANKACCTFROM"`
	CCACCTFROM    *CreditCardAccount                  `xml:"CCACCTFROM"`
	LOANACCTFROM  *LoanAccount                        `xml:"LOANACCTFROM"`
	OFXEXTENSION  *OFXExtensionType                   `xml:"OFXEXTENSION"`
	RECINTRATRNRQ []*RecurringIntraTransactionRequest `xml:"RECINTRATRNRQ"`
	*AbstractSyncRequest
}

// RecurringIntraSyncResponse is The OFX element "RECINTRASYNCRS" is of type "RecurringIntraSyncResponse"
type RecurringIntraSyncResponse struct {
	BANKACCTFROM  *BankAccount                         `xml:"BANKACCTFROM"`
	CCACCTFROM    *CreditCardAccount                   `xml:"CCACCTFROM"`
	LOANACCTFROM  *LoanAccount                         `xml:"LOANACCTFROM"`
	OFXEXTENSION  *OFXExtensionType                    `xml:"OFXEXTENSION"`
	RECINTRATRNRS []*RecurringIntraTransactionResponse `xml:"RECINTRATRNRS"`
	*AbstractSyncResponse
}

// RecurringIntraTransactionRequest is The OFX element "RECINTRATRNRQ" is of type "RecurringIntraTransactionRequest"
type RecurringIntraTransactionRequest struct {
	OFXEXTENSION  *OFXExtensionType                  `xml:"OFXEXTENSION"`
	RECINTRARQ    *RecurringIntraRequest             `xml:"RECINTRARQ"`
	RECINTRAMODRQ *RecurringIntraModRequest          `xml:"RECINTRAMODRQ"`
	RECINTRACANRQ *RecurringIntraCancellationRequest `xml:"RECINTRACANRQ"`
	*AbstractTransactionRequest
}

// RecurringIntraTransactionResponse is The OFX element "RECINTRATRNRS" is of type "RecurringIntraTransactionResponse"
type RecurringIntraTransactionResponse struct {
	OFXEXTENSION  *OFXExtensionType                   `xml:"OFXEXTENSION"`
	RECINTRARS    *RecurringIntraResponse             `xml:"RECINTRARS"`
	RECINTRAMODRS *RecurringIntraModResponse          `xml:"RECINTRAMODRS"`
	RECINTRACANRS *RecurringIntraCancellationResponse `xml:"RECINTRACANRS"`
	*AbstractTransactionResponse
}

// BankMailSyncRequest is The OFX element "BANKMAILSYNCRQ" is of type "BankMailSyncRequest"
type BankMailSyncRequest struct {
	INCIMAGES     string                        `xml:"INCIMAGES"`
	USEHTML       string                        `xml:"USEHTML"`
	BANKACCTFROM  *BankAccount                  `xml:"BANKACCTFROM"`
	CCACCTFROM    *CreditCardAccount            `xml:"CCACCTFROM"`
	OFXEXTENSION  *OFXExtensionType             `xml:"OFXEXTENSION"`
	BANKMAILTRNRQ []*BankMailTransactionRequest `xml:"BANKMAILTRNRQ"`
	*AbstractSyncRequest
}

// BankMailSyncResponse is The OFX element "BANKMAILSYNCRS" is of type "BankMailSyncResponse"
type BankMailSyncResponse struct {
	BANKACCTFROM  *BankAccount                   `xml:"BANKACCTFROM"`
	CCACCTFROM    *CreditCardAccount             `xml:"CCACCTFROM"`
	OFXEXTENSION  *OFXExtensionType              `xml:"OFXEXTENSION"`
	BANKMAILTRNRS []*BankMailTransactionResponse `xml:"BANKMAILTRNRS"`
	*AbstractSyncResponse
}
