// Code generated by xgen. DO NOT EDIT.

package schema

// SignonRequestMessage ...
type SignonRequestMessage struct {
}

// SignonResponseMessage ...
type SignonResponseMessage struct {
}

// RequestMessage ...
type RequestMessage struct {
}

// ResponseMessage ...
type ResponseMessage struct {
}

// ReferenceInfo ...
type ReferenceInfo struct {
}

// HeaderMessage ...
type HeaderMessage struct {
}
