// Code generated by xgen. DO NOT EDIT.

package gofx

// ImageTransactionRequest is The OFX element "IMAGETRNRQ" is of type "ImageTransactionRequest"
type ImageTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType `xml:"OFXEXTENSION"`
	IMAGERQ      *ImageRequest     `xml:"IMAGERQ"`
	*AbstractTransactionRequest
}
