// Code generated by xgen. DO NOT EDIT.

package schema

// InvestmentMailRequest is The OFX element "INVMAILRQ" is of type "InvestmentMailRequest"
type InvestmentMailRequest struct {
	INVACCTFROM *InvestmentAccount `xml:"INVACCTFROM"`
	MAIL        *Mail              `xml:"MAIL"`
}

// InvestmentMailResponse is The OFX element "INVMAILRS" is of type "InvestmentMailResponse"
type InvestmentMailResponse struct {
	INVACCTFROM *InvestmentAccount `xml:"INVACCTFROM"`
	MAIL        *Mail              `xml:"MAIL"`
}

// InvestmentStatementEndRequest is The OFX element "INVSTMTENDRQ" is of type "InvestmentStatementEndRequest"
type InvestmentStatementEndRequest struct {
	INVACCTFROM *InvestmentAccount `xml:"INVACCTFROM"`
	DTSTART     string             `xml:"DTSTART"`
	DTEND       string             `xml:"DTEND"`
	INCSTMTIMG  string             `xml:"INCSTMTIMG"`
}

// InvestmentStatementEndResponse is The OFX element "INVSTMTENDRS" is of type "InvestmentStatementEndResponse"
type InvestmentStatementEndResponse struct {
	CURDEF      string               `xml:"CURDEF"`
	INVACCTFROM *InvestmentAccount   `xml:"INVACCTFROM"`
	INVCLOSING  []*InvestmentClosing `xml:"INVCLOSING"`
}

// InvestmentStatementRequest is The OFX element "INVSTMTRQ" is of type "InvestmentStatementRequest"
type InvestmentStatementRequest struct {
	INVACCTFROM *InvestmentAccount `xml:"INVACCTFROM"`
	INCTRAN     *IncTransaction    `xml:"INCTRAN"`
	INCOO       string             `xml:"INCOO"`
	INCPOS      *IncPosition       `xml:"INCPOS"`
	INCBAL      string             `xml:"INCBAL"`
	INC401K     string             `xml:"INC401K"`
	INC401KBAL  string             `xml:"INC401KBAL"`
	INCTRANIMG  string             `xml:"INCTRANIMG"`
}

// InvestmentStatementResponse is The OFX element "INVSTMTRS" is of type "InvestmentStatementResponse"
type InvestmentStatementResponse struct {
	DTASOF      string                     `xml:"DTASOF"`
	CURDEF      string                     `xml:"CURDEF"`
	INVACCTFROM *InvestmentAccount         `xml:"INVACCTFROM"`
	INVTRANLIST *InvestmentTransactionList `xml:"INVTRANLIST"`
	INVPOSLIST  *InvestmentPositionList    `xml:"INVPOSLIST"`
	INVBAL      *InvestmentBalance         `xml:"INVBAL"`
	INVOOLIST   *InvestmentOpenOrderList   `xml:"INVOOLIST"`
	MKTGINFO    string                     `xml:"MKTGINFO"`
	INV401K     *Investment401k            `xml:"INV401K"`
	INV401KBAL  *Investment401kBalance     `xml:"INV401KBAL"`
}
