// Code generated by xgen. DO NOT EDIT.

package gofx

// CreditCardClosing is The OFX element "CCCLOSING" is of type "CreditCardClosing"
type CreditCardClosing struct {
	FITID              string           `xml:"FITID"`
	DTOPEN             string           `xml:"DTOPEN"`
	DTCLOSE            string           `xml:"DTCLOSE"`
	DTNEXT             string           `xml:"DTNEXT"`
	BALOPEN            string           `xml:"BALOPEN"`
	BALCLOSE           string           `xml:"BALCLOSE"`
	INTYTD             string           `xml:"INTYTD"`
	DTPMTDUE           string           `xml:"DTPMTDUE"`
	MINPMTDUE          string           `xml:"MINPMTDUE"`
	PASTDUEAMT         string           `xml:"PASTDUEAMT"`
	LATEFEEAMT         string           `xml:"LATEFEEAMT"`
	FINCHG             string           `xml:"FINCHG"`
	INTRATEPURCH       string           `xml:"INTRATEPURCH"`
	INTRATECASH        string           `xml:"INTRATECASH"`
	INTRATEXFER        string           `xml:"INTRATEXFER"`
	PAYANDCREDIT       string           `xml:"PAYANDCREDIT"`
	PURANDADV          string           `xml:"PURANDADV"`
	DEBADJ             string           `xml:"DEBADJ"`
	CREDITLIMIT        string           `xml:"CREDITLIMIT"`
	CASHADVBALAMT      string           `xml:"CASHADVBALAMT"`
	CASHADVAVAILAMT    string           `xml:"CASHADVAVAILAMT"`
	CASHADVCREDITLIMIT string           `xml:"CASHADVCREDITLIMIT"`
	DTPOSTSTART        string           `xml:"DTPOSTSTART"`
	DTPOSTEND          string           `xml:"DTPOSTEND"`
	AUTOPAY            string           `xml:"AUTOPAY"`
	LASTPMTINFO        *LastPmtInfoType `xml:"LASTPMTINFO"`
	REWARDINFO         *RewardInfoType  `xml:"REWARDINFO"`
	MKTGINFO           string           `xml:"MKTGINFO"`
	IMAGEDATA          *ImageData       `xml:"IMAGEDATA"`
	CURRENCY           *Currency        `xml:"CURRENCY"`
	ORIGCURRENCY       *Currency        `xml:"ORIGCURRENCY"`
}
