// Code generated by xgen. DO NOT EDIT.

package gofx

// SecurityListRequest is The OFX element "SECLISTRQ" is of type "SecurityListRequest"
type SecurityListRequest struct {
	SECRQ []*SecurityRequest `xml:"SECRQ"`
}

// SecurityRequest is The OFX element "SECRQ" is of type "SecurityRequest"
type SecurityRequest struct {
	SECID  *SecurityId `xml:"SECID"`
	TICKER string      `xml:"TICKER"`
	FIID   string      `xml:"FIID"`
}
