// Code generated by xgen. DO NOT EDIT.

package schema

// CheckStatusEnum is The OFX element "CHECKSTATUSENUM" is of type "CheckStatusEnum"
type CheckStatusEnum string

// AbstractCheckInfo ...
type AbstractCheckInfo struct {
}

// CheckDescription is The OFX element "CHKDESC" is of type "CheckDescription"
type CheckDescription struct {
	NAME     string `xml:"NAME"`
	CHECKNUM string `xml:"CHECKNUM"`
	DTUSER   string `xml:"DTUSER"`
	TRNAMT   string `xml:"TRNAMT"`
	*AbstractCheckInfo
}

// CheckRange is The OFX element "CHKRANGE" is of type "CheckRange"
type CheckRange struct {
	CHKNUMSTART string `xml:"CHKNUMSTART"`
	CHKNUMEND   string `xml:"CHKNUMEND"`
	*AbstractCheckInfo
}

// Closing is The OFX element "CLOSING" is of type "Closing"
type Closing struct {
	FITID          string              `xml:"FITID"`
	DTOPEN         string              `xml:"DTOPEN"`
	DTCLOSE        string              `xml:"DTCLOSE"`
	DTNEXT         string              `xml:"DTNEXT"`
	BALOPEN        string              `xml:"BALOPEN"`
	BALCLOSE       string              `xml:"BALCLOSE"`
	BALMIN         string              `xml:"BALMIN"`
	DEPANDCREDIT   string              `xml:"DEPANDCREDIT"`
	CHKANDDEB      string              `xml:"CHKANDDEB"`
	TOTALFEES      string              `xml:"TOTALFEES"`
	TOTALINT       string              `xml:"TOTALINT"`
	INTRATE        string              `xml:"INTRATE"`
	INTYTD         string              `xml:"INTYTD"`
	DTPOSTSTART    string              `xml:"DTPOSTSTART"`
	DTPOSTEND      string              `xml:"DTPOSTEND"`
	CREDITLINEINFO *CreditLineInfoType `xml:"CREDITLINEINFO"`
	MKTGINFO       string              `xml:"MKTGINFO"`
	IMAGEDATA      *ImageData          `xml:"IMAGEDATA"`
	CURRENCY       *Currency           `xml:"CURRENCY"`
	ORIGCURRENCY   *Currency           `xml:"ORIGCURRENCY"`
}

// StopCheckNumber is The OFX element "STPCHKNUM" is of type "StopCheckNumber"
type StopCheckNumber struct {
	CHECKNUM     string    `xml:"CHECKNUM"`
	NAME         string    `xml:"NAME"`
	DTUSER       string    `xml:"DTUSER"`
	TRNAMT       string    `xml:"TRNAMT"`
	CHKSTATUS    string    `xml:"CHKSTATUS"`
	CHKERROR     string    `xml:"CHKERROR"`
	CURRENCY     *Currency `xml:"CURRENCY"`
	ORIGCURRENCY *Currency `xml:"ORIGCURRENCY"`
}
