// Code generated by xgen. DO NOT EDIT.

package schema

// InterSyncRequest is The OFX element "INTERSYNCRQ" is of type "InterSyncRequest"
type InterSyncRequest struct {
	BANKACCTFROM *BankAccount               `xml:"BANKACCTFROM"`
	CCACCTFROM   *CreditCardAccount         `xml:"CCACCTFROM"`
	LOANACCTFROM *LoanAccount               `xml:"LOANACCTFROM"`
	OFXEXTENSION *OFXExtensionType          `xml:"OFXEXTENSION"`
	INTERTRNRQ   []*InterTransactionRequest `xml:"INTERTRNRQ"`
	*AbstractSyncRequest
}

// InterSyncResponse is The OFX element "INTERSYNCRS" is of type "InterSyncResponse"
type InterSyncResponse struct {
	BANKACCTFROM *BankAccount                `xml:"BANKACCTFROM"`
	CCACCTFROM   *CreditCardAccount          `xml:"CCACCTFROM"`
	LOANACCTFROM *LoanAccount                `xml:"LOANACCTFROM"`
	OFXEXTENSION *OFXExtensionType           `xml:"OFXEXTENSION"`
	INTERTRNRS   []*InterTransactionResponse `xml:"INTERTRNRS"`
	*AbstractSyncResponse
}

// InterTransactionRequest is The OFX element "INTERTRNRQ" is of type "InterTransactionRequest"
type InterTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType         `xml:"OFXEXTENSION"`
	INTERRQ      *InterRequest             `xml:"INTERRQ"`
	INTERMODRQ   *InterModRequest          `xml:"INTERMODRQ"`
	INTERCANRQ   *InterCancellationRequest `xml:"INTERCANRQ"`
	*AbstractTransactionRequest
}

// InterTransactionResponse is The OFX element "INTERTRNRS" is of type "InterTransactionResponse"
type InterTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType          `xml:"OFXEXTENSION"`
	INTERRS      *InterResponse             `xml:"INTERRS"`
	INTERMODRS   *InterModResponse          `xml:"INTERMODRS"`
	INTERCANRS   *InterCancellationResponse `xml:"INTERCANRS"`
	*AbstractTransactionResponse
}

// RecurringInterSyncRequest is The OFX element "RECINTERSYNCRQ" is of type "RecurringInterSyncRequest"
type RecurringInterSyncRequest struct {
	BANKACCTFROM  *BankAccount                        `xml:"BANKACCTFROM"`
	CCACCTFROM    *CreditCardAccount                  `xml:"CCACCTFROM"`
	LOANACCTFROM  *LoanAccount                        `xml:"LOANACCTFROM"`
	OFXEXTENSION  *OFXExtensionType                   `xml:"OFXEXTENSION"`
	RECINTERTRNRQ []*RecurringInterTransactionRequest `xml:"RECINTERTRNRQ"`
	*AbstractSyncRequest
}

// RecurringInterSyncResponse is The OFX element "RECINTERSYNCRS" is of type "RecurringInterSyncResponse"
type RecurringInterSyncResponse struct {
	BANKACCTFROM  *BankAccount                         `xml:"BANKACCTFROM"`
	CCACCTFROM    *CreditCardAccount                   `xml:"CCACCTFROM"`
	LOANACCTFROM  *LoanAccount                         `xml:"LOANACCTFROM"`
	OFXEXTENSION  *OFXExtensionType                    `xml:"OFXEXTENSION"`
	RECINTERTRNRS []*RecurringInterTransactionResponse `xml:"RECINTERTRNRS"`
	*AbstractSyncResponse
}

// RecurringInterTransactionRequest is The OFX element "RECINTERTRNRQ" is of type "RecurringInterTransactionRequest"
type RecurringInterTransactionRequest struct {
	OFXEXTENSION  *OFXExtensionType                  `xml:"OFXEXTENSION"`
	RECINTERRQ    *RecurringInterRequest             `xml:"RECINTERRQ"`
	RECINTERMODRQ *RecurringInterModRequest          `xml:"RECINTERMODRQ"`
	RECINTERCANRQ *RecurringInterCancellationRequest `xml:"RECINTERCANRQ"`
	*AbstractTransactionRequest
}

// RecurringInterTransactionResponse is The OFX element "RECINTERTRNRS" is of type "RecurringInterTransactionResponse"
type RecurringInterTransactionResponse struct {
	OFXEXTENSION  *OFXExtensionType                   `xml:"OFXEXTENSION"`
	RECINTERRS    *RecurringInterResponse             `xml:"RECINTERRS"`
	RECINTERMODRS *RecurringInterModResponse          `xml:"RECINTERMODRS"`
	RECINTERCANRS *RecurringInterCancellationResponse `xml:"RECINTERCANRS"`
	*AbstractTransactionResponse
}
