// Code generated by xgen. DO NOT EDIT.

package schema

// FindBillerTransactionRequest is The OFX element "FINDBILLERTRNRQ" is of type "FindBillerTransactionRequest"
type FindBillerTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType  `xml:"OFXEXTENSION"`
	FINDBILLERRQ *FindBillerRequest `xml:"FINDBILLERRQ"`
	*AbstractTransactionRequest
}

// FindBillerTransactionResponse is The OFX element "FINDBILLERTRNRS" is of type "FindBillerTransactionResponse"
type FindBillerTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType   `xml:"OFXEXTENSION"`
	FINDBILLERRS *FindBillerResponse `xml:"FINDBILLERRS"`
	*AbstractTransactionResponse
}
