// Code generated by xgen. DO NOT EDIT.

package schema

// CharTypeEnum is The OFX element "CHARTYPEENUM" is of type "CharTypeEnum"
type CharTypeEnum string

// ClientRoutingEnum is The OFX element "CLIENTROUTINGENUM" is of type "ClientRoutingEnum"
type ClientRoutingEnum string

// MessageSetCore is The OFX element "MSGSETCORE" is of type "MessageSetCore"
type MessageSetCore struct {
	VER          string            `xml:"VER"`
	URL          string            `xml:"URL"`
	OFXSEC       string            `xml:"OFXSEC"`
	TRANSPSEC    string            `xml:"TRANSPSEC"`
	SIGNONREALM  string            `xml:"SIGNONREALM"`
	LANGUAGE     []string          `xml:"LANGUAGE"`
	SYNCMODE     string            `xml:"SYNCMODE"`
	REFRESHSUPT  string            `xml:"REFRESHSUPT"`
	RESPFILEER   string            `xml:"RESPFILEER"`
	SPNAME       string            `xml:"SPNAME"`
	OFXEXTENSION *OFXExtensionType `xml:"OFXEXTENSION"`
}

// MessageSetMacro ...
type MessageSetMacro struct {
	SIGNUPMSGSET     *SignupMessageSet
	BANKMSGSET       *BankMessageSet
	CREDITCARDMSGSET *CreditcardMessageSet
	LOANMSGSET       *LoanMessageSet
	IMAGEMSGSET      *ImageMessageSet
	INVSTMTMSGSET    *InvestmentStatementMessageSet
	INTERXFERMSGSET  *InterTransferMessageSet
	WIREXFERMSGSET   *WireTransferMessageSet
	BILLPAYMSGSET    *BillPayMessageSet
	EMAILMSGSET      *EmailMessageSet
	SECLISTMSGSET    *SecurityListMessageSet
	PRESDIRMSGSET    *PresentmentDirMessageSet
	PRESDLVMSGSET    *PresentmentDlvMessageSet
}

// AbstractMessageSet ...
type AbstractMessageSet struct {
}

// AbstractMessageSetVersion ...
type AbstractMessageSetVersion struct {
	MSGSETCORE *MessageSetCore `xml:"MSGSETCORE"`
}

// SignupMessageSet is The OFX element "SIGNUPMSGSET" is of type "SignupMessageSet"
type SignupMessageSet struct {
	SIGNUPMSGSETV1 *SignupMessageSetV1 `xml:"SIGNUPMSGSETV1"`
	*AbstractMessageSet
}

// SignupMessageSetV1 is The OFX element "SIGNUPMSGSETV1" is of type "SignupMessageSetV1"
type SignupMessageSetV1 struct {
	CLIENTENROLL  *ClientEnroll `xml:"CLIENTENROLL"`
	WEBENROLL     *WebEnroll    `xml:"WEBENROLL"`
	OTHERENROLL   *OtherEnroll  `xml:"OTHERENROLL"`
	CHGUSERINFO   string        `xml:"CHGUSERINFO"`
	AVAILACCTS    string        `xml:"AVAILACCTS"`
	CLIENTACTREQ  string        `xml:"CLIENTACTREQ"`
	USERINFOAVAIL string        `xml:"USERINFOAVAIL"`
	*AbstractMessageSetVersion
}

// ClientEnroll is The OFX element "CLIENTENROLL" is of type "ClientEnroll"
type ClientEnroll struct {
	ACCTREQUIRED string `xml:"ACCTREQUIRED"`
}

// WebEnroll is The OFX element "WEBENROLL" is of type "WebEnroll"
type WebEnroll struct {
	URL string `xml:"URL"`
}

// OtherEnroll is The OFX element "OTHERENROLL" is of type "OtherEnroll"
type OtherEnroll struct {
	MESSAGE string `xml:"MESSAGE"`
}

// BankMessageSet is The OFX element "BANKMSGSET" is of type "BankMessageSet"
type BankMessageSet struct {
	BANKMSGSETV1 *BankMessageSetV1 `xml:"BANKMSGSETV1"`
	*AbstractMessageSet
}

// BankMessageSetV1 is The OFX element "BANKMSGSETV1" is of type "BankMessageSetV1"
type BankMessageSetV1 struct {
	INVALIDACCTTYPE []string          `xml:"INVALIDACCTTYPE"`
	CLOSINGAVAIL    string            `xml:"CLOSINGAVAIL"`
	PENDINGAVAIL    string            `xml:"PENDINGAVAIL"`
	XFERPROF        *TransferProfile  `xml:"XFERPROF"`
	STPCHKPROF      *StopCheckProfile `xml:"STPCHKPROF"`
	EMAILPROF       *EmailProfile     `xml:"EMAILPROF"`
	IMAGEPROF       *ImageProfile     `xml:"IMAGEPROF"`
	*AbstractMessageSetVersion
}

// TransferProfile is The OFX element "XFERPROF" is of type "TransferProfile"
type TransferProfile struct {
	PROCDAYSOFF   []string `xml:"PROCDAYSOFF"`
	PROCENDTM     string   `xml:"PROCENDTM"`
	CANSCHED      string   `xml:"CANSCHED"`
	CANRECUR      string   `xml:"CANRECUR"`
	CANLOAN       string   `xml:"CANLOAN"`
	CANSCHEDLOAN  string   `xml:"CANSCHEDLOAN"`
	CANRECURLOAN  string   `xml:"CANRECURLOAN"`
	CANMODXFERS   string   `xml:"CANMODXFERS"`
	CANMODMDLS    string   `xml:"CANMODMDLS"`
	MODELWND      string   `xml:"MODELWND"`
	DAYSWITH      string   `xml:"DAYSWITH"`
	DFLTDAYSTOPAY string   `xml:"DFLTDAYSTOPAY"`
}

// ImageProfile is The OFX element "IMAGEPROF" is of type "ImageProfile"
type ImageProfile struct {
	CLOSINGIMGAVAIL string `xml:"CLOSINGIMGAVAIL"`
	TRANIMGAVAIL    string `xml:"TRANIMGAVAIL"`
}

// CreditcardMessageSet is The OFX element "CREDITCARDMSGSET" is of type "CreditcardMessageSet"
type CreditcardMessageSet struct {
	CREDITCARDMSGSETV1 *CreditcardMessageSetV1 `xml:"CREDITCARDMSGSETV1"`
	*AbstractMessageSet
}

// CreditcardMessageSetV1 is The OFX element "CREDITCARDMSGSETV1" is of type "CreditcardMessageSetV1"
type CreditcardMessageSetV1 struct {
	CLOSINGAVAIL string        `xml:"CLOSINGAVAIL"`
	PENDINGAVAIL string        `xml:"PENDINGAVAIL"`
	IMAGEPROF    *ImageProfile `xml:"IMAGEPROF"`
	*AbstractMessageSetVersion
}

// LoanMessageSet is The OFX element "LOANMSGSET" is of type "LoanMessageSet"
type LoanMessageSet struct {
	LOANMSGSETV1 *LoanMessageSetV1 `xml:"LOANMSGSETV1"`
	*AbstractMessageSet
}

// LoanMessageSetV1 is The OFX element "LOANMSGSETV1" is of type "LoanMessageSetV1"
type LoanMessageSetV1 struct {
	TRANDNLD     string        `xml:"TRANDNLD"`
	CLOSINGAVAIL string        `xml:"CLOSINGAVAIL"`
	AMRTAVAIL    string        `xml:"AMRTAVAIL"`
	CANEMAIL     string        `xml:"CANEMAIL"`
	IMAGEPROF    *ImageProfile `xml:"IMAGEPROF"`
	*AbstractMessageSetVersion
}

// ImageMessageSet is The OFX element "IMAGEMSGSET" is of type "ImageMessageSet"
type ImageMessageSet struct {
	IMAGEMSGSETV1 *ImageMessageSetV1 `xml:"IMAGEMSGSETV1"`
	*AbstractMessageSet
}

// ImageMessageSetV1 is The OFX element "IMAGEMSGSETV1" is of type "ImageMessageSetV1"
type ImageMessageSetV1 struct {
	DFLTIMAGEDELAY string `xml:"DFLTIMAGEDELAY"`
	DFLTIMAGETTL   string `xml:"DFLTIMAGETTL"`
	*AbstractMessageSetVersion
}

// InvestmentStatementMessageSet is The OFX element "INVSTMTMSGSET" is of type "InvestmentStatementMessageSet"
type InvestmentStatementMessageSet struct {
	INVSTMTMSGSETV1 *InvestmentStatementMessageSetV1 `xml:"INVSTMTMSGSETV1"`
	*AbstractMessageSet
}

// InvestmentStatementMessageSetV1 is The OFX element "INVSTMTMSGSETV1" is of type "InvestmentStatementMessageSetV1"
type InvestmentStatementMessageSetV1 struct {
	TRANDNLD     string        `xml:"TRANDNLD"`
	OODNLD       string        `xml:"OODNLD"`
	POSDNLD      string        `xml:"POSDNLD"`
	BALDNLD      string        `xml:"BALDNLD"`
	CANEMAIL     string        `xml:"CANEMAIL"`
	INV401KDNLD  string        `xml:"INV401KDNLD"`
	CLOSINGAVAIL string        `xml:"CLOSINGAVAIL"`
	IMAGEPROF    *ImageProfile `xml:"IMAGEPROF"`
	*AbstractMessageSetVersion
}

// InterTransferMessageSet is The OFX element "INTERXFERMSGSET" is of type "InterTransferMessageSet"
type InterTransferMessageSet struct {
	INTERXFERMSGSETV1 *InterTransferMessageSetV1 `xml:"INTERXFERMSGSETV1"`
	*AbstractMessageSet
}

// InterTransferMessageSetV1 is The OFX element "INTERXFERMSGSETV1" is of type "InterTransferMessageSetV1"
type InterTransferMessageSetV1 struct {
	XFERPROF    *TransferProfile `xml:"XFERPROF"`
	CANBILLPAY  string           `xml:"CANBILLPAY"`
	CANCELWND   string           `xml:"CANCELWND"`
	DOMXFERFEE  string           `xml:"DOMXFERFEE"`
	INTLXFERFEE string           `xml:"INTLXFERFEE"`
	*AbstractMessageSetVersion
}

// WireTransferMessageSet is The OFX element "WIREXFERMSGSET" is of type "WireTransferMessageSet"
type WireTransferMessageSet struct {
	WIREXFERMSGSETV1 *WireTransferMessageSetV1 `xml:"WIREXFERMSGSETV1"`
	*AbstractMessageSet
}

// WireTransferMessageSetV1 is The OFX element "WIREXFERMSGSETV1" is of type "WireTransferMessageSetV1"
type WireTransferMessageSetV1 struct {
	PROCDAYSOFF []string `xml:"PROCDAYSOFF"`
	PROCENDTM   string   `xml:"PROCENDTM"`
	CANSCHED    string   `xml:"CANSCHED"`
	DOMXFERFEE  string   `xml:"DOMXFERFEE"`
	INTLXFERFEE string   `xml:"INTLXFERFEE"`
	*AbstractMessageSetVersion
}

// BillPayMessageSet is The OFX element "BILLPAYMSGSET" is of type "BillPayMessageSet"
type BillPayMessageSet struct {
	BILLPAYMSGSETV1 *BillPayMessageSetV1 `xml:"BILLPAYMSGSETV1"`
	*AbstractMessageSet
}

// BillPayMessageSetV1 is The OFX element "BILLPAYMSGSETV1" is of type "BillPayMessageSetV1"
type BillPayMessageSetV1 struct {
	DAYSWITH          string   `xml:"DAYSWITH"`
	DFLTDAYSTOPAY     string   `xml:"DFLTDAYSTOPAY"`
	XFERDAYSWITH      string   `xml:"XFERDAYSWITH"`
	XFERDFLTDAYSTOPAY string   `xml:"XFERDFLTDAYSTOPAY"`
	PROCDAYSOFF       []string `xml:"PROCDAYSOFF"`
	PROCENDTM         string   `xml:"PROCENDTM"`
	MODELWND          string   `xml:"MODELWND"`
	POSTPROCWND       string   `xml:"POSTPROCWND"`
	STSVIAMODS        string   `xml:"STSVIAMODS"`
	PMTBYADDR         string   `xml:"PMTBYADDR"`
	PMTBYXFER         string   `xml:"PMTBYXFER"`
	PMTBYPAYEEID      string   `xml:"PMTBYPAYEEID"`
	CANADDPAYEE       string   `xml:"CANADDPAYEE"`
	HASEXTDPMT        string   `xml:"HASEXTDPMT"`
	CANMODPMTS        string   `xml:"CANMODPMTS"`
	CANMODMDLS        string   `xml:"CANMODMDLS"`
	DIFFFIRSTPMT      string   `xml:"DIFFFIRSTPMT"`
	DIFFLASTPMT       string   `xml:"DIFFLASTPMT"`
	BILLPUBCONTEXT    string   `xml:"BILLPUBCONTEXT"`
	*AbstractMessageSetVersion
}

// EmailMessageSet is The OFX element "EMAILMSGSET" is of type "EmailMessageSet"
type EmailMessageSet struct {
	EMAILMSGSETV1 *EmailMessageSetV1 `xml:"EMAILMSGSETV1"`
	*AbstractMessageSet
}

// EmailMessageSetV1 is The OFX element "EMAILMSGSETV1" is of type "EmailMessageSetV1"
type EmailMessageSetV1 struct {
	MAILSUP    string `xml:"MAILSUP"`
	GETMIMESUP string `xml:"GETMIMESUP"`
	*AbstractMessageSetVersion
}

// PresentmentDirMessageSet is The OFX element "PRESDIRMSGSET" is of type "PresentmentDirMessageSet"
type PresentmentDirMessageSet struct {
	PRESDIRMSGSETV1 []*PresentmentDirMessageSetV1 `xml:"PRESDIRMSGSETV1"`
	*AbstractMessageSet
}

// PresentmentDirMessageSetV1 is The OFX element "PRESDIRMSGSETV1" is of type "PresentmentDirMessageSetV1"
type PresentmentDirMessageSetV1 struct {
	PRESDIRPROF *PresentmentDirProfile `xml:"PRESDIRPROF"`
	*AbstractMessageSetVersion
}

// PresentmentDirProfile is The OFX element "PRESDIRPROF" is of type "PresentmentDirProfile"
type PresentmentDirProfile struct {
	PROCDAYSOFF      []string `xml:"PROCDAYSOFF"`
	CANSUPPORTIMAGES string   `xml:"CANSUPPORTIMAGES"`
	PROCENDTM        string   `xml:"PROCENDTM"`
}

// SecurityListMessageSet is The OFX element "SECLISTMSGSET" is of type "SecurityListMessageSet"
type SecurityListMessageSet struct {
	SECLISTMSGSETV1 *SecurityListMessageSetV1 `xml:"SECLISTMSGSETV1"`
	*AbstractMessageSet
}

// SecurityListMessageSetV1 is The OFX element "SECLISTMSGSETV1" is of type "SecurityListMessageSetV1"
type SecurityListMessageSetV1 struct {
	SECLISTRQDNLD string `xml:"SECLISTRQDNLD"`
	*AbstractMessageSetVersion
}

// PresentmentDlvMessageSet is The OFX element "PRESDLVMSGSET" is of type "PresentmentDlvMessageSet"
type PresentmentDlvMessageSet struct {
	PRESDLVMSGSETV1 []*PresentmentDlvMessageSetV1 `xml:"PRESDLVMSGSETV1"`
	*AbstractMessageSet
}

// PresentmentDlvMessageSetV1 is The OFX element "PRESDLVMSGSETV1" is of type "PresentmentDlvMessageSetV1"
type PresentmentDlvMessageSetV1 struct {
	PRESDLVPROF *PresentmentDlvProfile `xml:"PRESDLVPROF"`
	EMAILPROF   *EmailProfile          `xml:"EMAILPROF"`
	*AbstractMessageSetVersion
}

// PresentmentDlvProfile is The OFX element "PRESDLVPROF" is of type "PresentmentDlvProfile"
type PresentmentDlvProfile struct {
	CANSUPPORTGROUPID        string   `xml:"CANSUPPORTGROUPID"`
	PROCDAYSOFF              []string `xml:"PROCDAYSOFF"`
	CANSUPPORTIMAGES         string   `xml:"CANSUPPORTIMAGES"`
	PROCENDTM                string   `xml:"PROCENDTM"`
	CANUPDATEPRESNAMEADDRESS string   `xml:"CANUPDATEPRESNAMEADDRESS"`
}

// StopCheckProfile is The OFX element "STPCHKPROF" is of type "StopCheckProfile"
type StopCheckProfile struct {
	PROCDAYSOFF []string `xml:"PROCDAYSOFF"`
	PROCENDTM   string   `xml:"PROCENDTM"`
	CANUSERANGE string   `xml:"CANUSERANGE"`
	CANUSEDESC  string   `xml:"CANUSEDESC"`
	STPCHKFEE   string   `xml:"STPCHKFEE"`
}

// EmailProfile is The OFX element "EMAILPROF" is of type "EmailProfile"
type EmailProfile struct {
	CANEMAIL  string `xml:"CANEMAIL"`
	CANNOTIFY string `xml:"CANNOTIFY"`
}

// DaysEnum is The OFX element "DAYSENUM" is of type "DaysEnum"
type DaysEnum string

// MAXMINType is The OFX element "MAXMIN" is of type "MAXMINType"
type MAXMINType string

// MessageSetList is The OFX element "MSGSETLIST" is of type "MessageSetList"
type MessageSetList struct {
	OfxMessageSetMacro *MessageSetMacro
	SIGNONMSGSET       *SignonMessageSet  `xml:"SIGNONMSGSET"`
	PROFMSGSET         *ProfileMessageSet `xml:"PROFMSGSET"`
}

// ProfileMessageSet is The OFX element "PROFMSGSET" is of type "ProfileMessageSet"
type ProfileMessageSet struct {
	PROFMSGSETV1 *ProfileMessageSetV1 `xml:"PROFMSGSETV1"`
	*AbstractMessageSet
}

// ProfileMessageSetV1 is The OFX element "PROFMSGSETV1" is of type "ProfileMessageSetV1"
type ProfileMessageSetV1 struct {
	*AbstractMessageSetVersion
}

// SecurityEnum is The OFX element "SECURITYENUM" is of type "SecurityEnum"
type SecurityEnum string

// SignonInfo is The OFX element "SIGNONINFO" is of type "SignonInfo"
type SignonInfo struct {
	SIGNONREALM       string `xml:"SIGNONREALM"`
	MIN               string `xml:"MIN"`
	MAX               string `xml:"MAX"`
	CHARTYPE          string `xml:"CHARTYPE"`
	CASESEN           string `xml:"CASESEN"`
	SPECIAL           string `xml:"SPECIAL"`
	SPACES            string `xml:"SPACES"`
	PINCH             string `xml:"PINCH"`
	CHGPINFIRST       string `xml:"CHGPINFIRST"`
	USERCRED1LABEL    string `xml:"USERCRED1LABEL"`
	USERCRED2LABEL    string `xml:"USERCRED2LABEL"`
	CLIENTUIDREQ      string `xml:"CLIENTUIDREQ"`
	AUTHTOKENFIRST    string `xml:"AUTHTOKENFIRST"`
	AUTHTOKENLABEL    string `xml:"AUTHTOKENLABEL"`
	AUTHTOKENINFOURL  string `xml:"AUTHTOKENINFOURL"`
	MFACHALLENGESUPT  string `xml:"MFACHALLENGESUPT"`
	MFACHALLENGEFIRST string `xml:"MFACHALLENGEFIRST"`
	ACCESSTOKENREQ    string `xml:"ACCESSTOKENREQ"`
}

// SignonInfoList is The OFX element "SIGNONINFOLIST" is of type "SignonInfoList"
type SignonInfoList struct {
	SIGNONINFO []*SignonInfo `xml:"SIGNONINFO"`
}

// SignonMessageSet is The OFX element "SIGNONMSGSET" is of type "SignonMessageSet"
type SignonMessageSet struct {
	SIGNONMSGSETV1 *SignonMessageSetV1 `xml:"SIGNONMSGSETV1"`
	*AbstractMessageSet
}

// SignonMessageSetV1 is The OFX element "SIGNONMSGSETV1" is of type "SignonMessageSetV1"
type SignonMessageSetV1 struct {
	*AbstractMessageSetVersion
}

// SyncEnum is The OFX element "SYNCENUM" is of type "SyncEnum"
type SyncEnum string

// VersionType is The OFX element "VER" is of type "VersionType"
type VersionType string

// MFATextType is The OFX element "USERCRED1LABEL" is of type "MFATextType"
//
//	The OFX element "USERCRED2LABEL" is of type "MFATextType"
type MFATextType string

// MFAUrlType is The OFX element "AUTHTOKENINFOURL" is of type "MFAUrlType"
type MFAUrlType string
