// Code generated by xgen. DO NOT EDIT.

package gofx

// AccountRequest is The OFX element "ACCTRQ" is of type "AccountRequest"
type AccountRequest struct {
	SVCADD *ServiceAdd    `xml:"SVCADD"`
	SVCCHG *ServiceChange `xml:"SVCCHG"`
	SVCDEL *ServiceDelete `xml:"SVCDEL"`
	SVC    string         `xml:"SVC"`
}

// AccountResponse is The OFX element "ACCTRS" is of type "AccountResponse"
type AccountResponse struct {
	SVCADD    *ServiceAdd    `xml:"SVCADD"`
	SVCCHG    *ServiceChange `xml:"SVCCHG"`
	SVCDEL    *ServiceDelete `xml:"SVCDEL"`
	SVC       string         `xml:"SVC"`
	SVCSTATUS string         `xml:"SVCSTATUS"`
}

// ChangeUserInfoRequest is The OFX element "CHGUSERINFORQ" is of type "ChangeUserInfoRequest"
type ChangeUserInfoRequest struct {
	FIRSTNAME  string `xml:"FIRSTNAME"`
	MIDDLENAME string `xml:"MIDDLENAME"`
	LASTNAME   string `xml:"LASTNAME"`
	ADDR1      string `xml:"ADDR1"`
	ADDR2      string `xml:"ADDR2"`
	ADDR3      string `xml:"ADDR3"`
	CITY       string `xml:"CITY"`
	STATE      string `xml:"STATE"`
	POSTALCODE string `xml:"POSTALCODE"`
	COUNTRY    string `xml:"COUNTRY"`
	DAYPHONE   string `xml:"DAYPHONE"`
	EVEPHONE   string `xml:"EVEPHONE"`
	EMAIL      string `xml:"EMAIL"`
}

// ChangeUserInfoResponse is The OFX element "CHGUSERINFORS" is of type "ChangeUserInfoResponse"
type ChangeUserInfoResponse struct {
	FIRSTNAME  string `xml:"FIRSTNAME"`
	MIDDLENAME string `xml:"MIDDLENAME"`
	LASTNAME   string `xml:"LASTNAME"`
	ADDR1      string `xml:"ADDR1"`
	ADDR2      string `xml:"ADDR2"`
	ADDR3      string `xml:"ADDR3"`
	CITY       string `xml:"CITY"`
	STATE      string `xml:"STATE"`
	POSTALCODE string `xml:"POSTALCODE"`
	COUNTRY    string `xml:"COUNTRY"`
	DAYPHONE   string `xml:"DAYPHONE"`
	EVEPHONE   string `xml:"EVEPHONE"`
	EMAIL      string `xml:"EMAIL"`
	DTINFOCHG  string `xml:"DTINFOCHG"`
}

// EnrollRequest is The OFX element "ENROLLRQ" is of type "EnrollRequest"
type EnrollRequest struct {
	FIRSTNAME    string              `xml:"FIRSTNAME"`
	MIDDLENAME   string              `xml:"MIDDLENAME"`
	LASTNAME     string              `xml:"LASTNAME"`
	ADDR1        string              `xml:"ADDR1"`
	ADDR2        string              `xml:"ADDR2"`
	ADDR3        string              `xml:"ADDR3"`
	CITY         string              `xml:"CITY"`
	STATE        string              `xml:"STATE"`
	POSTALCODE   string              `xml:"POSTALCODE"`
	COUNTRY      string              `xml:"COUNTRY"`
	DAYPHONE     string              `xml:"DAYPHONE"`
	EVEPHONE     string              `xml:"EVEPHONE"`
	EMAIL        string              `xml:"EMAIL"`
	USERID       string              `xml:"USERID"`
	TAXID        string              `xml:"TAXID"`
	SECURITYNAME string              `xml:"SECURITYNAME"`
	DATEBIRTH    string              `xml:"DATEBIRTH"`
	BANKACCTFROM *BankAccount        `xml:"BANKACCTFROM"`
	CCACCTFROM   *CreditCardAccount  `xml:"CCACCTFROM"`
	INVACCTFROM  *InvestmentAccount  `xml:"INVACCTFROM"`
	PRESACCTFROM *PresentmentAccount `xml:"PRESACCTFROM"`
}

// EnrollResponse is The OFX element "ENROLLRS" is of type "EnrollResponse"
type EnrollResponse struct {
	TEMPPASS string `xml:"TEMPPASS"`
	USERID   string `xml:"USERID"`
	DTEXPIRE string `xml:"DTEXPIRE"`
}
