// Code generated by xgen. DO NOT EDIT.

package schema

// BillStatusModTransactionRequest is The OFX element "BILLSTATUSMODTRNRQ" is of type "BillStatusModTransactionRequest"
type BillStatusModTransactionRequest struct {
	OFXEXTENSION    *OFXExtensionType     `xml:"OFXEXTENSION"`
	BILLSTATUSMODRQ *BillStatusModRequest `xml:"BILLSTATUSMODRQ"`
	*AbstractTransactionRequest
}

// BillStatusModTransactionResponse is The OFX element "BILLSTATUSMODTRNRS" is of type "BillStatusModTransactionResponse"
type BillStatusModTransactionResponse struct {
	OFXEXTENSION    *OFXExtensionType      `xml:"OFXEXTENSION"`
	BILLSTATUSMODRS *BillStatusModResponse `xml:"BILLSTATUSMODRS"`
	*AbstractTransactionResponse
}

// BillTableStructureTransactionRequest is The OFX element "BILLTBLSTRUCTTRNRQ" is of type "BillTableStructureTransactionRequest"
type BillTableStructureTransactionRequest struct {
	OFXEXTENSION    *OFXExtensionType          `xml:"OFXEXTENSION"`
	BILLTBLSTRUCTRQ *BillTableStructureRequest `xml:"BILLTBLSTRUCTRQ"`
	*AbstractTransactionRequest
}

// BillTableStructureTransactionResponse is The OFX element "BILLTBLSTRUCTTRNRS" is of type "BillTableStructureTransactionResponse"
type BillTableStructureTransactionResponse struct {
	OFXEXTENSION    *OFXExtensionType           `xml:"OFXEXTENSION"`
	BILLTBLSTRUCTRS *BillTableStructureResponse `xml:"BILLTBLSTRUCTRS"`
	*AbstractTransactionResponse
}

// PresentmentDetailTransactionRequest is The OFX element "PRESDETAILTRNRQ" is of type "PresentmentDetailTransactionRequest"
type PresentmentDetailTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType         `xml:"OFXEXTENSION"`
	PRESDETAILRQ *PresentmentDetailRequest `xml:"PRESDETAILRQ"`
	*AbstractTransactionRequest
}

// PresentmentDetailTransactionResponse is The OFX element "PRESDETAILTRNRS" is of type "PresentmentDetailTransactionResponse"
type PresentmentDetailTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType          `xml:"OFXEXTENSION"`
	PRESDETAILRS *PresentmentDetailResponse `xml:"PRESDETAILRS"`
	*AbstractTransactionResponse
}

// PresentmentGroupAccountInfoTransactionRequest is The OFX element "PRESGRPACCTINFOTRNRQ" is of type "PresentmentGroupAccountInfoTransactionRequest"
type PresentmentGroupAccountInfoTransactionRequest struct {
	USERID       string              `xml:"USERID"`
	GROUPID      string              `xml:"GROUPID"`
	OFXEXTENSION *OFXExtensionType   `xml:"OFXEXTENSION"`
	ACCTINFORQ   *AccountInfoRequest `xml:"ACCTINFORQ"`
	*AbstractTransactionRequest
}

// PresentmentGroupAccountInfoTransactionResponse is The OFX element "PRESGRPACCTINFOTRNRS" is of type "PresentmentGroupAccountInfoTransactionResponse"
type PresentmentGroupAccountInfoTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType    `xml:"OFXEXTENSION"`
	ACCTINFORS   *AccountInfoResponse `xml:"ACCTINFORS"`
	*AbstractTransactionResponse
}

// PresentmentListTransactionRequest is The OFX element "PRESLISTTRNRQ" is of type "PresentmentListTransactionRequest"
type PresentmentListTransactionRequest struct {
	USERID       string                  `xml:"USERID"`
	GROUPID      string                  `xml:"GROUPID"`
	OFXEXTENSION *OFXExtensionType       `xml:"OFXEXTENSION"`
	PRESLISTRQ   *PresentmentListRequest `xml:"PRESLISTRQ"`
	*AbstractTransactionRequest
}

// PresentmentListTransactionResponse is The OFX element "PRESLISTTRNRS" is of type "PresentmentListTransactionResponse"
type PresentmentListTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType        `xml:"OFXEXTENSION"`
	PRESLISTRS   *PresentmentListResponse `xml:"PRESLISTRS"`
	*AbstractTransactionResponse
}

// PresentmentMailSyncRequest is The OFX element "PRESMAILSYNCRQ" is of type "PresentmentMailSyncRequest"
type PresentmentMailSyncRequest struct {
	INCIMAGES     string                               `xml:"INCIMAGES"`
	USEHTML       string                               `xml:"USEHTML"`
	PRESACCTFROM  *PresentmentAccount                  `xml:"PRESACCTFROM"`
	OFXEXTENSION  *OFXExtensionType                    `xml:"OFXEXTENSION"`
	PRESMAILTRNRQ []*PresentmentMailTransactionRequest `xml:"PRESMAILTRNRQ"`
	*AbstractSyncRequest
}

// PresentmentMailSyncResponse is The OFX element "PRESMAILSYNCRS" is of type "PresentmentMailSyncResponse"
type PresentmentMailSyncResponse struct {
	PRESACCTFROM  *PresentmentAccount                   `xml:"PRESACCTFROM"`
	OFXEXTENSION  *OFXExtensionType                     `xml:"OFXEXTENSION"`
	PRESMAILTRNRS []*PresentmentMailTransactionResponse `xml:"PRESMAILTRNRS"`
	*AbstractSyncResponse
}

// PresentmentMailTransactionRequest is The OFX element "PRESMAILTRNRQ" is of type "PresentmentMailTransactionRequest"
type PresentmentMailTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType       `xml:"OFXEXTENSION"`
	PRESMAILRQ   *PresentmentMailRequest `xml:"PRESMAILRQ"`
	*AbstractTransactionRequest
}

// PresentmentMailTransactionResponse is The OFX element "PRESMAILTRNRS" is of type "PresentmentMailTransactionResponse"
type PresentmentMailTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType        `xml:"OFXEXTENSION"`
	PRESMAILRS   *PresentmentMailResponse `xml:"PRESMAILRS"`
	*AbstractTransactionResponse
}

// PresentmentNotifyTransactionRequest is The OFX element "PRESNOTIFYTRNRQ" is of type "PresentmentNotifyTransactionRequest"
type PresentmentNotifyTransactionRequest struct {
	OFXEXTENSION *OFXExtensionType         `xml:"OFXEXTENSION"`
	PRESNOTIFYRQ *PresentmentNotifyRequest `xml:"PRESNOTIFYRQ"`
	*AbstractTransactionRequest
}

// PresentmentNotifyTransactionResponse is The OFX element "PRESNOTIFYTRNRS" is of type "PresentmentNotifyTransactionResponse"
type PresentmentNotifyTransactionResponse struct {
	OFXEXTENSION *OFXExtensionType          `xml:"OFXEXTENSION"`
	PRESNOTIFYRS *PresentmentNotifyResponse `xml:"PRESNOTIFYRS"`
	*AbstractTransactionResponse
}
