// Code generated by xgen. DO NOT EDIT.

package gofx

// CreditCardStatementEndRequest is The OFX element "CCSTMTENDRQ" is of type "CreditCardStatementEndRequest"
type CreditCardStatementEndRequest struct {
	CCACCTFROM *CreditCardAccount `xml:"CCACCTFROM"`
	DTSTART    string             `xml:"DTSTART"`
	DTEND      string             `xml:"DTEND"`
	INCSTMTIMG string             `xml:"INCSTMTIMG"`
}

// CreditCardStatementEndResponse is The OFX element "CCSTMTENDRS" is of type "CreditCardStatementEndResponse"
type CreditCardStatementEndResponse struct {
	CURDEF     string               `xml:"CURDEF"`
	CCACCTFROM *CreditCardAccount   `xml:"CCACCTFROM"`
	CCCLOSING  []*CreditCardClosing `xml:"CCCLOSING"`
}

// CreditCardStatementRequest is The OFX element "CCSTMTRQ" is of type "CreditCardStatementRequest"
type CreditCardStatementRequest struct {
	CCACCTFROM     *CreditCardAccount `xml:"CCACCTFROM"`
	INCTRAN        *IncTransaction    `xml:"INCTRAN"`
	INCLUDEPENDING string             `xml:"INCLUDEPENDING"`
	INCTRANIMG     string             `xml:"INCTRANIMG"`
}

// CreditCardStatementResponse is The OFX element "CCSTMTRS" is of type "CreditCardStatementResponse"
type CreditCardStatementResponse struct {
	CURDEF             string                  `xml:"CURDEF"`
	CCACCTFROM         *CreditCardAccount      `xml:"CCACCTFROM"`
	BANKTRANLIST       *BankTransactionList    `xml:"BANKTRANLIST"`
	BANKTRANLISTP      *PendingTransactionList `xml:"BANKTRANLISTP"`
	LEDGERBAL          *LedgerBalance          `xml:"LEDGERBAL"`
	AVAILBAL           *AvailableBalance       `xml:"AVAILBAL"`
	CASHADVBALAMT      string                  `xml:"CASHADVBALAMT"`
	CASHADVAVAILAMT    string                  `xml:"CASHADVAVAILAMT"`
	CASHADVCREDITLIMIT string                  `xml:"CASHADVCREDITLIMIT"`
	INTRATEPURCH       string                  `xml:"INTRATEPURCH"`
	INTRATECASH        string                  `xml:"INTRATECASH"`
	INTRATEXFER        string                  `xml:"INTRATEXFER"`
	REWARDINFO         *RewardInfoType         `xml:"REWARDINFO"`
	BALLIST            *BalanceList            `xml:"BALLIST"`
	MKTGINFO           string                  `xml:"MKTGINFO"`
}
