// Code generated by xgen. DO NOT EDIT.

package schema

// OFXTransactionRequestMessage ...
type OFXTransactionRequestMessage struct {
	TransactionRequest *AbstractTransactionRequest `xml:"TransactionRequest"`
	*RequestMessage
}

// OFXTransactionResponseMessage ...
type OFXTransactionResponseMessage struct {
	TransactionResponse *AbstractTransactionResponse `xml:"TransactionResponse"`
	*ResponseMessage
}

// OFXSynchronizationRequestMessage ...
type OFXSynchronizationRequestMessage struct {
	SynchronizationRequest *AbstractSyncRequest `xml:"SynchronizationRequest"`
	*RequestMessage
}

// OFXSynchronizationResponseMessage ...
type OFXSynchronizationResponseMessage struct {
	SynchronizationResponse *AbstractSyncResponse `xml:"SynchronizationResponse"`
	*ResponseMessage
}

// OFXSignonRequestMessage ...
type OFXSignonRequestMessage struct {
	SignonRequest *SignonRequest `xml:"SignonRequest"`
	*SignonRequestMessage
}

// OFXSignonResponseMessage ...
type OFXSignonResponseMessage struct {
	SignonResponse *SignonResponse `xml:"SignonResponse"`
	*SignonResponseMessage
}

// OFXHeaderMessage ...
type OFXHeaderMessage struct {
	OFXHEADER  string `xml:"OFXHEADER"`
	VERSION    string `xml:"VERSION"`
	SECURITY   string `xml:"SECURITY"`
	OLDFILEUID string `xml:"OLDFILEUID"`
	NEWFILEUID string `xml:"NEWFILEUID"`
	*HeaderMessage
}

// SecuritiesListInfo ...
type SecuritiesListInfo struct {
	SecurityList *SecurityList `xml:"SecurityList"`
	*ReferenceInfo
}
